name: 'todo-to-markdown'
description: 'Todo to markdown converter - converts your todo file for use in readme.md'
author: 'Indeedornot'
runs:
  using: 'node16'
  main: 'dist/index.js'

inputs:
  GH_TOKEN:
    description: 'GitHub access token with Repo scope'
    default: ${{ github.token }}
    required: true
